import { event, exam, task } from "./types";

// Suponiendo que hoy es new Date(), octubre de 2025
const currentYear = new Date().getFullYear();
const currentMonth = new Date().getMonth();

export const defaultEvents: event[] = [
  {
    id: 0,
    type: "personal",
    date: new Date(currentYear, currentMonth, 3),
    allDay: true,
    startTime: new Date(currentYear, currentMonth, 3, 0, 0),
    finishedTime: new Date(currentYear, currentMonth, 3, 23, 59),
    color: 1,
    name: "Cena con amigos",
    description: "Cena en el restaurante italiano del centro.",
  },
  {
    id: 1,
    type: 2,
    date: new Date(currentYear, currentMonth, 5),
    allDay: false,
    startTime: new Date(currentYear, currentMonth, 5, 16, 0),
    finishedTime: new Date(currentYear, currentMonth, 5, 18, 30),
    color: 2,
    name: "Reunión de proyecto escolar",
    subject: 2,
  },
  {
    id: 2,
    type: "job",
    date: new Date(currentYear, currentMonth, 5),
    allDay: false,
    startTime: new Date(currentYear, currentMonth, 5, 9, 30),
    finishedTime: new Date(currentYear, currentMonth, 5, 11, 0),
    color: 3,
    name: "Entrega de presentación",
    description: "Subir presentación a la plataforma antes del mediodía.",
  },
  {
    id: 3,
    type: "other",
    date: new Date(currentYear, currentMonth, 7),
    allDay: false,
    startTime: new Date(currentYear, currentMonth, 7, 15, 0),
    finishedTime: new Date(currentYear, currentMonth, 8, 12, 0),
    color: 4,
    name: "Hackathon escolar (2 días)",
    description: "Competencia de programación en equipos.",
  },
  {
    id: 4,
    type: "personal",
    date: new Date(currentYear, currentMonth, 10),
    allDay: false,
    startTime: new Date(currentYear, currentMonth, 10, 18, 0),
    finishedTime: new Date(currentYear, currentMonth, 10, 20, 0),
    color: 1,
    name: "Ir al cine",
  },
  {
    id: 5,
    type: 1,
    date: new Date(currentYear, currentMonth, 10),
    allDay: false,
    startTime: new Date(currentYear, currentMonth, 10, 9, 0),
    finishedTime: new Date(currentYear, currentMonth, 10, 10, 0),
    color: 5,
    name: "Revisión de código en grupo",
    subject: 1,
  },
  {
    id: 6,
    type: "job",
    date: new Date(currentYear, currentMonth, 12),
    allDay: true,
    startTime: new Date(currentYear, currentMonth, 12, 0, 0),
    finishedTime: new Date(currentYear, currentMonth, 13, 0, 0),
    color: 3,
    name: "Jornada de puertas abiertas (2 días)",
    description: "Ayudar en la organización y recepción.",
  },
  {
    id: 7,
    type: "personal",
    date: new Date(currentYear, currentMonth, 14),
    allDay: false,
    startTime: new Date(currentYear, currentMonth, 14, 17, 30),
    finishedTime: new Date(currentYear, currentMonth, 14, 19, 0),
    color: 1,
    name: "Entrenamiento físico",
  },
  {
    id: 8,
    type: "other",
    date: new Date(currentYear, currentMonth, 21),
    allDay: false,
    startTime: new Date(currentYear, currentMonth, 21, 8, 0),
    finishedTime: new Date(currentYear, currentMonth, 22, 14, 0),
    color: 4,
    name: "Viaje corto de estudios (2 días)",
  },
];

export const defaultExams: exam[] = [
  {
    id: 0,
    date: new Date(currentYear, currentMonth, 5),
    allDay: false,
    startTime: new Date(currentYear, currentMonth, 5, 9, 0),
    finishedTime: new Date(currentYear, currentMonth, 5, 10, 0),
    notifications: [],
    name: "Examen de Matemáticas",
    subject: 2,
    description: "Temas 1 y 2: álgebra y ecuaciones.",
  },
  {
    id: 1,
    date: new Date(currentYear, currentMonth, 14),
    allDay: false,
    startTime: new Date(currentYear, currentMonth, 14, 8, 30),
    finishedTime: new Date(currentYear, currentMonth, 14, 9, 30),
    notifications: [],
    name: "Examen de Historia",
    subject: 3,
  },
  {
    id: 2,
    date: new Date(currentYear, currentMonth, 18),
    allDay: false,
    startTime: new Date(currentYear, currentMonth, 18, 11, 0),
    finishedTime: new Date(currentYear, currentMonth, 18, 12, 0),
    notifications: [],
    name: "Examen de Inglés",
    subject: 1,
  },
  {
    id: 3,
    date: new Date(currentYear, currentMonth, 25),
    allDay: false,
    startTime: new Date(currentYear, currentMonth, 25, 10, 0),
    finishedTime: new Date(currentYear, currentMonth, 25, 11, 0),
    notifications: [],
    name: "Examen de Biología",
    subject: 4,
  },
  {
    id: 4,
    date: new Date(currentYear, currentMonth, 25),
    allDay: false,
    startTime: new Date(currentYear, currentMonth, 25, 12, 0),
    finishedTime: new Date(currentYear, currentMonth, 25, 13, 0),
    notifications: [],
    name: "Examen de Música",
    subject: 5,
  },
];

export const defaultTasks: task[] = [
  {
    id: 0,
    name: "Redactar ensayo de literatura",
    notifications: [],
    status: "inProgress",
    subject: 1,
    description: "Ensayo sobre 'Don Quijote'.",
  },
  {
    id: 1,
    name: "Preparar presentación de física",
    notifications: [],
    status: "pending",
    subject: 2,
  },
  {
    id: 2,
    name: "Revisar apuntes de historia",
    notifications: [],
    status: "pending",
    subject: 3,
  },
  {
    id: 3,
    name: "Terminar boceto para arte",
    notifications: [],
    status: "inProgress",
    subject: "personal",
  },
  {
    id: 4,
    name: "Estudiar para examen de biología",
    notifications: [],
    status: "pending",
    subject: 4,
    finishedDate: new Date(currentYear, currentMonth, 24),
  },
  {
    id: 5,
    name: "Actualizar app del proyecto",
    notifications: [],
    status: "pending",
    subject: 2,
  },
  {
    id: 6,
    name: "Practicar guitarra 30 minutos",
    notifications: [],
    status: "inProgress",
    subject: "personal",
  },
  {
    id: 7,
    name: "Subir tarea de inglés a Moodle",
    notifications: [],
    status: "inProgress",
    subject: 1,
    finishedDate: new Date(currentYear, currentMonth, 17),
  },
  {
    id: 8,
    name: "Organizar archivos del proyecto",
    notifications: [],
    status: "pending",
    subject: "personal",
  },
  {
    id: 9,
    name: "Revisar notas del simulacro",
    notifications: [],
    status: "pending",
    subject: 2,
  },
];
